runtime: python39  # You can change this to another runtime if needed

handlers:
  - url: /
    static_files: register.html
    upload: register.html

  - url: /src/styles/(.*)
    static_files: src/styles/\1
    upload: src/styles/(.*)

  - url: /src/scripts/(.*)
    static_files: src/scripts/\1
    upload: src/scripts/(.*)

  - url: /src/images/(.*)
    static_files: src/images/\1
    upload: src/images/(.*)

  - url: /(.*)
    static_files: \1
    upload: (.*)